/*    HTTP Host:  b.static.ak.fbcdn.net                                        */
/*    Generated:  November 3rd 2009 10:23:22 AM PST                            */
/*      Machine:  10.16.140.106                                                */
/*       Source:  Local Cache                                                  */
/*     Location:  rsrc:4:ava9at0w                                              */
/*       Locale:  nu_ll                                                        */
/*         Path:  js/lib/primer.js                                             */

!function(){var doc=document,htm=doc.documentElement,phc='DOMControl_placeholder',lct=null,_L4=function(elm,tag){while(elm&&elm.nodeName!=tag)elm=elm.parentNode;return elm;},fob=function(e){var e=e||window.event,elm=e.target||e.srcElement,ph=elm.getAttribute('placeholder');if(ph)if('focus'==e.type||'focusin'==e.type){if(elm.value==ph){elm.value='';CSS.removeClass(elm,phc);}}else if(elm.value==''){CSS.addClass(elm,phc);elm.value=ph;}};$=window.$||function(id){var e=doc.getElementById(id);return (e&&e.getAttribute('id')==id)?e:null;};CSS=window.CSS||{addClass:function(e,c){e.className+=' '+c;},removeClass:function(e,c){e.className=e.className.replace(new RegExp('(^|\\s)'+c+'(?=\\s|$)','g'),' ');}};var _L6={_preloaded:[],_pending:[],loadComponents:function(_L7,_L8){_L7=_L7 instanceof Array?_L7:[_L7];_L6._pending.push({components:_L7,callback:_L8});var _L9=doc.createElement('script');_L9.type='text/javascript';_L9.src='/rsrcx.php?'+(window.Bootloader.realBootloader?'':'boot&')+'enable='+_L7.join(',');doc.getElementsByTagName('head')[0].appendChild(_L9);},done:function(_L7){_L6._preloaded.push(_L7);}};window.Bootloader=window.Bootloader||_L6;htm.onclick=function(e){e=e||window.event;lct=e.target||e.srcElement;var _L8=_L4(lct,'A')||htm,_L9=_L8.getAttribute('ajaxify')||_L8.href;switch(_L8.rel){case 'dialog':case 'dialog-post':Bootloader.loadComponents('dialog',function(){Dialog.bootstrap(_L9,null,_L8.rel=='dialog');});break;case 'async':case 'async-post':Bootloader.loadComponents('async',function(){AsyncRequest.bootstrap(_L9,_L8);});break;default:return;}return false;};htm.onsubmit=function(e){e=e||window.event;var _L8=e.target||e.srcElement;if(!_L8||_L8.nodeName!='FORM'||!_L8.getAttribute('ajaxify'))return;Bootloader.loadComponents(['async','dom-form'],function(){var _L9=_L8.method.toUpperCase();new AsyncRequest(_L8.action).setData(serialize_form(_L8,lct)).setReadOnly(_L9=='GET').setMethod(_L9).setStatusElement(_L8).send();});return false;};htm.onfocusin=htm.onfocusout=fob;if(htm.addEventListener){htm.addEventListener('focus',fob,true);htm.addEventListener('blur',fob,true);}CSS.removeClass(htm,'no_js');}();

if (window.Bootloader) { Bootloader.done(["js\/lib\/primer.js"]); }